from __future__ import annotations

from pathlib import Path
from typing import List

from .handoff import collect_handoff_data, render_handoff
from .scanner import detect_commands
from .utils import read_text, safe_tree, write_text

MAX_SECTION_CHARS = 12_000


def create_context_pack(root: Path, output: str = "PROJECT_CONTEXT.md") -> Path:
    content = render_context_pack(root)
    output_path = root / output
    write_text(output_path, content)
    return output_path


def render_context_pack(root: Path) -> str:
    lines: List[str] = []
    lines.append("# PROJECT_CONTEXT.md")
    lines.append("")
    lines.append("This file was generated by `agentctx pack` for an AI coding session.")
    lines.append("")
    lines.append("## Repository")
    lines.append("")
    lines.append(f"- Name: `{root.name}`")
    lines.append("")
    lines.append("## Files To Read First")
    lines.append("")
    for name in ["AGENTS.md", "README.md", "HANDOFF.md", "pyproject.toml", "package.json"]:
        if (root / name).exists():
            lines.append(f"- `{name}`")
    lines.append("")
    lines.append("## Project Structure")
    lines.append("")
    lines.append("```text")
    tree = safe_tree(root)
    lines.extend(tree if tree else ["."])
    lines.append("```")
    lines.append("")
    lines.append("## Detected Commands")
    lines.append("")
    commands = detect_commands(root)
    for kind in ["install", "test", "build"]:
        values = commands.get(kind, [])
        lines.append(f"- {kind.title()}: {', '.join(values) if values else 'not detected'}")
    lines.append("")
    _append_file_section(lines, root, "README.md", "README Summary")
    _append_file_section(lines, root, "AGENTS.md", "Agent Instructions")
    if (root / "HANDOFF.md").exists():
        _append_file_section(lines, root, "HANDOFF.md", "Current Handoff")
    else:
        data = collect_handoff_data(root)
        lines.append("## Current Handoff")
        lines.append("")
        lines.append(render_handoff(data).rstrip())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _append_file_section(lines: List[str], root: Path, filename: str, title: str) -> None:
    path = root / filename
    if not path.exists() or not path.is_file():
        return
    content = read_text(path, limit=MAX_SECTION_CHARS)
    truncated = path.stat().st_size > MAX_SECTION_CHARS
    lines.append(f"## {title}")
    lines.append("")
    lines.append(f"Source: `{filename}`")
    lines.append("")
    lines.append("```md")
    lines.append(content.rstrip())
    if truncated:
        lines.append("\n... truncated ...")
    lines.append("```")
    lines.append("")
